### ISSUE TITLE
LoadSettings Error

### ISSUE THREAD

**Issue by nancikennedy** [crudos/SimpleMacro#20]
On Retail (11.0.2), using SM v11.0.0.2...

1x SimpleMacro/SimpleMacro.lua:62: attempt to call method 'LoadSettings' (a nil value)
[string "@SimpleMacro/SimpleMacro.lua"]:62: in function <SimpleMacro/SimpleMacro.lua:40>

Locals:
self = SimpleMacro {
 settings = <table> {
 }
 SettingsCategory = <table> {
 }
 dbc = <table> {
 }
 dba = <table> {
 }
}
event = "ADDON_LOADED"
arg1 = "SimpleMacro"
gt = <table> {
 groups = <table> {
 }
}
(*temporary) = nil
(*temporary) = SimpleMacroSettings {
}
(*temporary) = "attempt to call method 'LoadSettings' (a nil value)"
addonName = "SimpleMacro"
C = <table> {
 CONDITIONAL_EDITOR = <table> {
 }
 CREATE_FRAME = <table> {
 }
 MACRO_FRAME = <table> {
 }
 MACRO_EDITOR = <table> {
 }
 SETTINGS = <table> {
 }
 CHANGE_FRAME = <table> {
 }
 GROUP_FRAME = <table> {
 }
 tabs = <table> {
 }
}

**Comment by crudos** [comment]
fixed with https://github.com/crudos/SimpleMacro/issues/23
