### ISSUE TITLE
Shared Settings Error #1

### ISSUE THREAD

**Issue by nancikennedy** [crudos/SimpleMacro#21]
On Retail (11.0.2), using SM v11.0.0.2...

2x ...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:351: attempt to call method 'GetVariableType' (a nil value)
[string "@Blizzard_Settings_Shared/Blizzard_Settings.lua"]:351: in function `CreateCheckboxInitializer'
[string "@Blizzard_Settings_Shared/Blizzard_Settings.lua"]:375: in function <...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:374>
[string "=(tail call)"]: ?
[string "@SimpleMacro/settings/settings.lua"]:46: in main chunk

Locals:
setting = <table> {
 order = 78
 ID = 78
 name = "SimpleMacro"
 subcategories = <table> {
 }
}
options = nil
tooltip = "Allows you to update the target of a group by right-clicking a unit frame."
(*temporary) = nil
(*temporary) = <table> {
 order = 78
 ID = 78
 name = "SimpleMacro"
 subcategories = <table> {
 }
}
(*temporary) = "attempt to call method 'GetVariableType' (a nil value)"

**Comment by crudos** [comment]
fixed in https://github.com/crudos/SimpleMacro/issues/23
