### ISSUE TITLE
Shared Settings Error #2

### ISSUE THREAD

**Issue by nancikennedy** [crudos/SimpleMacro#22]
On Retail (11.0.2), using SM v11.0.0.2...

2x Blizzard_Settings_Shared/Blizzard_Setting.lua:383: 'variableTbl' argument must be a table.
[string "=[C]"]: in function `assert'
[string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:383: in function `Init'
[string "@Blizzard_SharedXMLBase/Mixin.lua"]:28: in function <Blizzard_SharedXMLBase/Mixin.lua:26>
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:197: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:155>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:98: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:97>
[string "=(tail call)"]: ?
[string "@SimpleMacro/settings/settings.lua"]:44: in main chunk

Locals:
(*temporary) = false
(*temporary) = "'variableTbl' argument must be a table."

**Comment by crudos** [comment]
fixed in https://github.com/crudos/SimpleMacro/issues/23
