### ISSUE TITLE
XML Errors

### ISSUE THREAD

**Issue by nancikennedy** [crudos/SimpleMacro#23]
On Retail (11.0.2), using SM v11.0.0.2...

2x SimpleMacro/settings/settings.xml:5 Frame SimpleMacroSettings: Unknown method OnLoad in element OnLoad
2x SimpleMacro/settings/settings.xml:3 SimpleMacroSettings: Has bad mixin: SimpleMacroSettingsMixin
1x SimpleMacro/settings/settings.xml:7 Frame SimpleMacroSettings: Unknown method OnHide in element OnHide
1x SimpleMacro/settings/settings.xml:6 Frame SimpleMacroSettings: Unknown method OnShow in element OnShow

**Comment by crudos** [comment]
Should be fixed with latest commit 369cd6af7c4e60973aaca76f533815e9a97a168a
